"""Add file_data BLOB

Revision ID: 5fbc8c0b9328
Revises: 
Create Date: 2026-02-19 05:07:03.398429

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5fbc8c0b9328'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doc_versions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_data', sa.LargeBinary(), nullable=True))

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_data', sa.LargeBinary(), nullable=True))
        batch_op.alter_column('filepath',
               existing_type=mysql.VARCHAR(length=512),
               nullable=True)
        batch_op.create_unique_constraint(None, ['share_link_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('filepath',
               existing_type=mysql.VARCHAR(length=512),
               nullable=False)
        batch_op.drop_column('file_data')

    with op.batch_alter_table('doc_versions', schema=None) as batch_op:
        batch_op.drop_column('file_data')

    # ### end Alembic commands ###
